#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	[ -c /dev/lcd ] || return

	echo -n "touch_start" > /dev/lcd 2>/dev/null
	sleep 1

	procd_open_instance lcd_render
	procd_set_param command /usr/bin/lcd_render
	procd_set_param respawn
	procd_close_instance

	procd_open_instance touch_poll
	procd_set_param command /usr/bin/touch_poll daemon_fg
	procd_set_param respawn
	procd_close_instance

	procd_open_instance data_collector
	procd_set_param command /usr/bin/data_collector
	procd_set_param respawn
	procd_close_instance

	sleep 2

	procd_open_instance lcd_ui
	procd_set_param command /usr/bin/ucode /usr/bin/lcd_ui.uc
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	killall touch_poll 2>/dev/null
}
